/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.handlemanager.jooqrepository;


import eu.dissco.core.handlemanager.jooqrepository.tables.Handles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.handles</code>.
     */
    public static final Handles HANDLES = Handles.HANDLES;
}
