/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.handlemanager.jooqobjects.tables.records;


import eu.dissco.core.handlemanager.jooqobjects.tables.ManualPid;

import org.jooq.impl.TableRecordImpl;


/**
 * PIDs from which the PID manager may pull
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ManualPidRecord extends TableRecordImpl<ManualPidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.manual_pid.pid</code>. Persistent identifier
     */
    public void setPid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.manual_pid.pid</code>. Persistent identifier
     */
    public String getPid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.manual_pid.prefix</code>. One of: TEST, SANDBOX,
     * 20.5000.1025, 10.3535
     */
    public void setPrefix(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.manual_pid.prefix</code>. One of: TEST, SANDBOX,
     * 20.5000.1025, 10.3535
     */
    public String getPrefix() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManualPidRecord
     */
    public ManualPidRecord() {
        super(ManualPid.MANUAL_PID);
    }

    /**
     * Create a detached, initialised ManualPidRecord
     */
    public ManualPidRecord(String pid, String prefix) {
        super(ManualPid.MANUAL_PID);

        setPid(pid);
        setPrefix(prefix);
        resetChangedOnNotNull();
    }
}
