/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.handlemanager.jooqobjects;


import eu.dissco.core.handlemanager.jooqobjects.tables.ManualPid;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * PIDs from which the PID manager may pull
     */
    public static final ManualPid MANUAL_PID = ManualPid.MANUAL_PID;
}
